{{- if gt .Values.transmogrifierCount 0.0 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-transmogrifier
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.transmogrifierCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
        rucio-daemon: transmogrifier
    spec:
      volumes:
      - name: proxy-volume
        secret:
          secretName: prod-rucio-x509up
      - name: ca-volume
        secret:
          secretName: prod-rucio-ca-bundle
      {{- range $key, $val := .Values.additionalSecrets }}
      - name: {{ $key }}
        secret:
          secretName: {{ $.Release.Name }}-{{ $val.secretName }}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: proxy-volume
              mountPath: /opt/proxy
            - name: ca-volume
              mountPath: /opt/certs
            {{- range $key, $val := .Values.additionalSecrets }}
            - name: {{ $key }}
              mountPath: {{ $val.mountPath }}
              subPath: {{ $val.subPath }}
            {{- end}}
          env:
            {{- range $key1, $val1 := .Values.config }}
            {{- range $key2, $val2 := $val1}}
            - name: RUCIO_CFG_{{ $key1 | upper }}_{{ $key2 | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key1 }}_{{ $key2 }}
            {{- end}}
            {{- end}}
            - name: RUCIO_DAEMON
              value: "transmogrifier"
            - name: RUCIO_DAEMON_ARGS
              value: "{{- if .Values.transmogrifier.threads }} --threads {{ .Values.transmogrifier.threads }}{{end}} {{- if .Values.transmogrifier.bulk }} --bulk {{ .Values.transmogrifier.bulk }}{{ end }}{{- if .Values.transmogrifier.sleepTime }} --sleep-time {{ .Values.transmogrifier.sleepTime }}{{ end }}"
            - name: RUCIO_CFG_DATABASE_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: database-default
{{- with .Values.transmogrifier.resources }}
          resources:
{{ toYaml . | trim | indent 12 }}
{{ end }}
{{- with .Values.transmogrifier.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.transmogrifier.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.transmogrifier.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{ end }}
