{{- if gt .Values.traceReplicaCount 0.0 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rucio.fullname" . }}-trace
  labels:
    app: {{ template "rucio.name" . }}-trace
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.traceReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}-trace
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}-trace
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
      volumes:
      - name: httpdlog
        emptyDir: {}
      {{- range $key, $val := .Values.additionalSecrets }}
      - name: {{ $key }}
        secret:
          secretName: {{ $.Release.Name }}-{{ $val.secretName }}
      {{- end}}
{{- if .Values.useSSL.traceServer }}
      - name: hostcert
        secret:
          secretName: {{ .Release.Name }}-trace-hostcert
      - name: hostkey
        secret:
          secretName: {{ .Release.Name }}-trace-hostkey
      - name: cafile
        secret:
          secretName: {{ .Release.Name }}-trace-cafile
{{- end }}
      containers:
{{- if .Values.exposeErrorLogs.traceServer }}
        - name: httpd-error-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -f /var/log/httpd/error_log']
          volumeMounts:
          - name: httpdlog
            mountPath: /var/log/httpd
{{- end }}
{{- if .Values.monitoring.enabled }}
        - name: apache-exporter
          image: rucio/apache_exporter
{{- if .Values.useSSL.traceServer }}
          args: ['--telemetry.address=:{{ .Values.monitoring.exporterPort }}', '--scrape_uri=https://localhost/server-status/?auto', '--insecure']
{{ else }}
          args: ['--telemetry.address=:{{ .Values.monitoring.exporterPort }}']
{{ end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.monitoring.exporterPort }}
              protocol: TCP
{{- end }}
        - name: {{ .Chart.Name }}-trace
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: httpdlog
              mountPath: /var/log/httpd
{{- if .Values.useSSL.traceServer }}
            - name: hostcert
              mountPath: /etc/grid-security/hostcert.pem
              subPath: hostcert.pem
            - name: hostkey
              mountPath: /etc/grid-security/hostkey.pem
              subPath: hostkey.pem
            - name: cafile
              mountPath: /etc/grid-security/ca.pem
              subPath: ca.pem
            {{- range $key, $val := .Values.additionalSecrets }}
            - name: {{ $key }}
              mountPath: {{ $val.mountPath }}
              subPath: {{ $val.subPath }}
            {{- end}}
{{- end }}
          env:
            {{- range $key, $val := .Values.httpd_config }}
            - name: RUCIO_HTTPD_{{ $key | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key }}
            {{- end}}
            {{- range $key1, $val1 := .Values.config }}
            {{- range $key2, $val2 := $val1}}
            - name: RUCIO_CFG_{{ $key1 | upper }}_{{ $key2 | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key1 }}_{{ $key2 }}
            {{- end}}
            {{- end}}
{{- if .Values.useSSL.traceServer }}
            - name: RUCIO_ENABLE_SSL
              value: "True"
            - name: OPENSSL_ALLOW_PROXY_CERTS
              value: "1"
{{- else }}
            - name: RUCIO_ENABLE_SSL
              value: "False"
{{- end }}
            - name: RUCIO_SERVER_TYPE
              value: "trace"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
            - name: RUCIO_CFG_DATABASE_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: database-default
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
